<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>GARbro.GUI.Linux</AssemblyName>
    <RootNamespace>GARbro.GUI.Linux</RootNamespace>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <Nullable>disable</Nullable>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GameRes/GameRes.Portable.csproj" />
    <ProjectReference Include="../ArcFormats/ArcFormats.Portable.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
  </ItemGroup>
</Project>
