<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>GARbro.Console</AssemblyName>
    <RootNamespace>GARbro</RootNamespace>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ConsoleBrowser.cs" />
    <Compile Include="Properties/AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GameRes/GameRes.Portable.csproj" />
    <ProjectReference Include="../ArcFormats/ArcFormats.Portable.csproj" />
  </ItemGroup>
</Project>
