<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ArcFormats</AssemblyName>
    <RootNamespace>GameRes.Formats</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Portable/AssemblyAnchor.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GameRes/GameRes.Portable.csproj" />
  </ItemGroup>
</Project>
